events { }

http {
    # Resolver DNS pour resoudre le domaine AlwaysData
    resolver 8.8.8.8 ipv6=off;

    # split_clients repartit les utilisateurs en 2 groupes (A/B testing 50/50)
    # En fonction d'une variable aleatoire, on choisit la version cible
    split_clients "${remote_addr}${remote_port}" $ab_target {
        50%     "/spring/";
        *       "/django/";
    }

    server {
        listen 80;

        location /test {
            # Redirige vers la version A ou B selon le split (50/50)
            proxy_pass https://g66239.alwaysdata.net$ab_target;
            proxy_set_header Host g66239.alwaysdata.net;
            proxy_ssl_server_name on;
        }
    }
}
