# Image officielle Nginx, version alpine pour rester leger
FROM nginx:alpine
LABEL author="66045"

# Remplace la conf par defaut par notre conf personnalisee
COPY nginx.conf /etc/nginx/nginx.conf

# Port d'ecoute du serveur Nginx
EXPOSE 80
